networks:
  laravel_network_station:
services:
  server:
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
    container_name: laravel_server
    networks:
      - laravel_network_station
  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
    container_name: laravel_php
    networks:
      - laravel_network_station
  mysql:
    image: mysql:8.0.1
    restart: unless-stopped
    tty: true
    container_name: laravel_mysql
    env_file:
      - mysql/.env
    ports:
      - 3307:3306
    networks:
      - laravel_network_station
    volumes:
      - ./mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    container_name: laravel_phpmyadmin
    depends_on:
      - mysql
    ports:
      - 8090:80
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=^0BmjiTE3i1^@)=&&^h^
    networks:
      - laravel_network_station
  composer:
    build:
      context: .
      dockerfile: dockerfiles/composer.dockerfile
    volumes:
      - ./src:/var/www/html
    depends_on:
      - php
    networks:
      - laravel_network_station
  artisan:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: [ "php", "/var/www/html/artisan" ]
    networks:
      - laravel_network_station
